#!/bin/bash

if [ $# -ne 2 ]
then
	echo "Usage: convertFromPinto in.pinto out.xyz"
	exit -1
fi

./pintoToRgba/pintoToRgba rgba $1 | convert -depth 8 -size `./pintoToRgba/pintoToRgba getSize $1` rgba:- $2
